[env]
monitor_speed = 115200

[pico-base]
extra_scripts = post:version_build.py
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#651837d09a1a58c46bd1bcf4647468d8c5ed92c2
framework = arduino

build_unflags =
    -Os

board_build.core = earlephilhower
#board_build.filesystem_size = 512k

upload_protocol = mbed
#upload_protocol = cmsis-dap
debug_tool = cmsis-dap

build_src_filter =
    +<*.cpp>

lib_ldf_mode = chain+
lib_extra_dirs = ${sysenv.USERPROFILE}/.platformio/packages/framework-arduinopico/ota
lib_deps = 
	bodmer/TFT_eSPI@^2.5.43
    xreef/PCF8574 library@^2.3.7
    greiman/SdFat@^2.3.1

build_flags =
	-O3
	-I.
    -Isrc/tft-espi-config
    -Ilib
    -DENABLE_SOUND=1
    -DCROWPANEL_PWM_AUDIO=1
    -DENABLE_LCD=1
    -DENABLE_SDCARD=1
    -DENABLE_INPUT=3
    -DENABLE_LCD_DMA=1
    -DENABLE_LCD_FRAMEBUFFER=0
    -DENABLE_FRAMEBUFFER_FLIP_X_Y=0
    -DENABLE_DOUBLE_BUFFERING=0
    -DENABLE_USB_STORAGE_DEVICE=0
    -DPEANUT_FULL_GBC_SUPPORT=1
    -DPEANUT_GB_HIGH_LCD_ACCURACY=0
    -DCROWPANEL_ILI9341=1
    -DUSE_TINYUSB

[env:pico]
extends = pico-base
board = rpipico
# Reserve ~1MB for ROMs, i.e. ~800KB for code
board_build.filesystem_size = 1280k

[env:pico2]
extends = pico-base
board = rpipico2
# Reserve 3MB for ROMs, i.e. 1MB for code
board_build.filesystem_size = 3072k
